current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of hadoop.application at integrations 2c934eb5223b
    columns:
    - name: hadoop_application_allocated_mb
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.allocated.mb'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_allocated_v_cores
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.allocated.v_cores'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: hadoop.application.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: hadoop_application_memory_seconds
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.memory_seconds'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_progress
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.progress'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_running_containers
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.running_containers'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_time_elapsed
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.time.elapsed'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: hadoop_application_time_finished
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.time.finished'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: hadoop_application_time_started
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.time.started'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: hadoop_application_vcore_seconds
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: hadoop.application.vcore_seconds'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
