current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of forgerock.idm_config at integrations 2c934eb5223b
    columns:
    - name: forgerock_changedFields
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.changedFields'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: forgerock_eventName
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.eventName'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: forgerock_level
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.level'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: forgerock_objectId
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.objectId'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: forgerock_source
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.source'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: forgerock_topic
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: forgerock.topic'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
