base: meta/elastic/ecs
base_version: "1.0.0"
current: "1.0.0"
versions:
  "1.0.0":
    date: "2026-10-04"
    summary: grafana.logs selection from meta/elastic/ecs
    select:
    - name: client_ip
      index: dimension
    - name: cloud_account_id
      index: exact_match
    - name: cloud_availability_zone
      index: exact_match
    - name: cloud_instance_id
      index: exact_match
    - name: cloud_provider
      index: exact_match
    - name: cloud_region
      index: exact_match
    - name: container_id
      index: exact_match
    - name: data_stream_dataset
      index: exact_match
    - name: data_stream_namespace
      index: exact_match
    - name: data_stream_type
      index: exact_match
    - name: event_dataset
      index: exact_match
    - name: event_duration
      index: range
    - name: event_ingested
      index: range
    - name: event_kind
      index: exact_match
    - name: event_module
      index: exact_match
    - name: event_severity
      index: range
    - name: host_name
      index: exact_match
    - name: http_request_method
      index: exact_match
    - name: http_request_referrer
      index: exact_match
    - name: http_response_body_bytes
      index: range
    - name: http_response_status_code
      index: range
    - name: log_level
      index: exact_match
    - name: log_logger
      index: exact_match
    - name: log_origin_file_line
      index: range
    - name: log_origin_file_name
      index: exact_match
    - name: message
      index: word_search
    - name: url_path
      index: exact_match
    - name: user_name
      index: exact_match
