current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of aws_bedrock_agentcore.memory_application_logs at integrations 2c934eb5223b
    columns:
    - name: aws_bedrock_agentcore_memory_actor_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.actor_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_conversation_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.conversation_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_memory_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.memory_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_memory_strategy
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.memory_strategy'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_memory_strategy_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.memory_strategy_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_namespace
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.namespace'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_operation_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.operation_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_payload_object
      type: json
      attribute:
      - not_null
      cardinality: unknown
      expr: '@source: aws.bedrock_agentcore.memory.payload_object'
      comment: 'Elasticsearch mapping type: flattened'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_provider_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.provider_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_request_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.request_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_resource_arn
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.resource_arn'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_session_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.bedrock_agentcore.memory.session_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_bedrock_agentcore_memory_severity_number
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: aws.bedrock_agentcore.memory.severity_number'
      comment: 'Elasticsearch mapping type: integer'
      _field_type: base
    - name: aws_cloudwatch_message
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: aws.cloudwatch.message'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: cloud_image_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: cloud.image.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_containerized
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: host.containerized'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: host_os_build
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.build'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_os_codename
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.codename'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
