-- =============================================================================
-- DFE Schema DDL: detection_checkpoint
-- Hunt execution checkpoint tracking
-- Generated by: dfe-engine DDLFileWriter
--
-- This file was auto-generated. Use {db} as database placeholder.
-- =============================================================================
CREATE TABLE IF NOT EXISTS {db}.detection_checkpoint
(
    `_org_id` LowCardinality(String) COMMENT 'Org id (tenant identifier) that was scanned' CODEC(ZSTD(1)),
    `rule_name` LowCardinality(String) COMMENT 'Name of the rule that was executed' CODEC(ZSTD(1)),
    `thread_id` LowCardinality(String) COMMENT 'Identifier for the execution thread' CODEC(ZSTD(1)),
    `log_buffer` Int32 COMMENT 'Log-ingestion lag buffer in seconds, subtracted from the scheduled start time so late-arriving logs land before the scan window closes' CODEC(ZSTD(1)),
    `query_schedule_time` DateTime64(3,'UTC') COMMENT 'Scheduled time for the rule execution' CODEC(Delta, ZSTD(1)),
    `execution_time` DateTime64(3,'UTC') COMMENT 'Actual time when the rule execution started' CODEC(Delta, ZSTD(1)),
    `end_time` DateTime64(3,'UTC') COMMENT 'Actual time when the rule execution ended' CODEC(Delta, ZSTD(1)),
    `previous_successful_checkpoint` DateTime64(3,'UTC') COMMENT 'query_checkpoint_time of the previous successful run for this org/hunt/rule; forms the inclusive lower bound of this runs scan window' CODEC(Delta, ZSTD(1)),
    `query_checkpoint_time` DateTime64(3,'UTC') COMMENT 'Scan-window high-watermark (scheduled_start_time minus log_buffer seconds); the exclusive upper bound of this runs window and the lower bound of the next run' CODEC(Delta, ZSTD(1)),
    `execution_time_ms` Int32 COMMENT 'Wall-clock time of the detection query execution in milliseconds (end_time minus execution_time)' CODEC(ZSTD(1)),
    `hunt_name` LowCardinality(String) COMMENT 'Name of the parent hunt' CODEC(ZSTD(1)),
    `query_id` LowCardinality(String) COMMENT 'Per-execution UUID assigned to the query and passed to ClickHouse, used to correlate this run with system.query_log' CODEC(ZSTD(1)),
    `explain_plan` String COMMENT 'Query execution plan for performance analysis' CODEC(ZSTD(1)),
    `explain_duration_ms` Int32 COMMENT 'Time taken to generate the explain plan in milliseconds' CODEC(ZSTD(1)),
    `scheduling_mode` LowCardinality(String) DEFAULT 'adaptive' COMMENT 'Scheduling mode for the rule execution: adaptive (REFRESH AFTER backpressure) or cron (rigid, deprecated). Defaults to adaptive' CODEC(ZSTD(1)),
    `read_rows` Int64 COMMENT 'Number of rows read during query execution' CODEC(ZSTD(1)),
    `read_bytes` Int64 COMMENT 'Number of bytes read during query execution' CODEC(ZSTD(1)),
    `memory_usage` Int64 COMMENT 'Peak memory usage in bytes during query execution' CODEC(ZSTD(1)),
    `result_rows` Int64 COMMENT 'Number of rows returned by the detection query' CODEC(ZSTD(1)),
    `query_fingerprint` LowCardinality(String) COMMENT 'Fingerprint of the query for identifying similar queries across executions' CODEC(ZSTD(1))
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(query_checkpoint_time)
PRIMARY KEY (`_org_id`, `hunt_name`, `rule_name`, `query_checkpoint_time`)
ORDER BY (`_org_id`, `hunt_name`, `rule_name`, `query_checkpoint_time`)
SETTINGS
    index_granularity = 2048,
    ttl_only_drop_parts = 1;
