-- =============================================================================
-- DFE Schema DDL: dfe_audit.detection_checkpoint
-- Purpose: Hunt execution checkpoint tracking
-- Generated by: dfe-engine DDLFileWriter
--
-- This file is auto-generated. Use {db} as database placeholder.
-- =============================================================================

CREATE TABLE IF NOT EXISTS {db}.detection_checkpoint
(
    _org_id LowCardinality(String) CODEC(LZ4),
    rule_name LowCardinality(String) CODEC(LZ4),
    thread_id LowCardinality(String) CODEC(LZ4),
    log_buffer UInt32 CODEC(Delta, ZSTD),
    query_schedule_time DateTime CODEC(DoubleDelta, LZ4),
    execution_time DateTime CODEC(DoubleDelta, LZ4),
    end_time DateTime CODEC(DoubleDelta, LZ4),
    previous_successful_checkpoint DateTime CODEC(DoubleDelta, LZ4),
    query_checkpoint_time DateTime CODEC(DoubleDelta, LZ4),
    execution_time_ms Int32 CODEC(Delta, ZSTD),
    hunt_name LowCardinality(String) CODEC(LZ4),
    query_id LowCardinality(String) CODEC(LZ4),
    explain_plan String DEFAULT '' CODEC(ZSTD),
    explain_duration_ms Int32 DEFAULT 0 CODEC(Delta, ZSTD),
    scheduling_mode LowCardinality(String) DEFAULT 'adaptive' CODEC(LZ4),
    read_rows UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
    read_bytes UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
    memory_usage UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
    result_rows UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
    query_fingerprint LowCardinality(String) DEFAULT '' CODEC(LZ4)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(query_checkpoint_time)
ORDER BY (_org_id, hunt_name, rule_name, query_checkpoint_time);
