-- =============================================================================
-- DFE Schema DDL: Profile reference: passthrough
-- Profile: passthrough
-- Reference DDL for the passthrough common header profile
-- Generated by: dfe-engine DDLFileWriter
--
-- This file is auto-generated. Use {db} as database placeholder.
-- =============================================================================
CREATE TABLE IF NOT EXISTS {db}._passthrough_profile
(
    `_timestamp_load` DateTime64(3,'UTC') DEFAULT now64(3) CODEC(Delta, LZ4) COMMENT '@generated: now64(3) — Insertion timestamp (ms precision)',
    `_uuid` Nullable(UUID) DEFAULT generateUUIDv7() COMMENT '@generated: generateUUIDv7() — Time-ordered unique event identifier',
    `_org_id` LowCardinality(String) CODEC(ZSTD(1)) COMMENT '@source: org_id — Tenant/organisation identifier',
    `_json` Nullable(JSON) CODEC(ZSTD(3)) COMMENT '@captured: raw_payload as JSON — Original event payload as structured JSON',
    INDEX idx__org_id `_org_id` TYPE set(0) GRANULARITY 4
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(_timestamp_load)
PRIMARY KEY (`_timestamp_load`, `_org_id`)
ORDER BY (`_timestamp_load`, `_org_id`)
TTL _timestamp + INTERVAL 90 DAY DELETE WHERE _timestamp >= 0,
    _timestamp_load + INTERVAL 90 DAY DELETE WHERE _timestamp_load >= 0
COMMENT '@schema_version: 2 | @profile: passthrough | @profile_version: 1.0.0'
SETTINGS
    index_granularity = 2048,
    ttl_only_drop_parts = 1;
