current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of sentinel_one.application at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_account_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.account.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_application_installation_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.application_installation_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_application_installation_path
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.application_installation_path'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_application_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.application_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_application_vendor
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.application_vendor'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_application_versions_count
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.application_versions_count'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_core_count
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.core_count'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_cpe
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.cpe'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_cpu_count
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.cpu_count'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_detection_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.detection_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_endpoint_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.endpoint_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_endpoint_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.endpoint_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_endpoint_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.endpoint_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_endpoint_uuid
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.endpoint_uuid'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_endpoints_count
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.endpoints_count'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_estimate
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: sentinel_one.application.estimate'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: sentinel_one_application_file_size
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application.file_size'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_group_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.group_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_os_arch
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.os_arch'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_os_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.os_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_os_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.os_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_os_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.os_version'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application.version'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_site_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.site.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
