current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of sentinel_one.application_risk at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: labels_is_transform_source
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: labels.is_transform_source'
      comment: 'Elasticsearch mapping type: constant_keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_application
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.application'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_application_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.application_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_application_vendor
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.application_vendor'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_application_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.application_version'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_base_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.base_score'
      comment: 'Elasticsearch mapping type: float'
      _field_type: base
    - name: sentinel_one_application_risk_cve_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.cve_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_cvss_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.cvss_version'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_days_detected
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.days_detected'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: sentinel_one_application_risk_detection_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.detection_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_risk_endpoint_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.endpoint_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_endpoint_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.endpoint_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_endpoint_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.endpoint_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_exploit_code_maturity
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.exploit_code_maturity'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_last_scan_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.last_scan_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_risk_last_scan_result
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.last_scan_result'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_mark_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.mark_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_marked_by
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.marked_by'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_marked_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.marked_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_risk_mitigation_status
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.mitigation_status'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_mitigation_status_change_time
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.mitigation_status_change_time'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_risk_mitigation_status_changed_by
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.mitigation_status_changed_by'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_mitigation_status_reason
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.mitigation_status_reason'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_nvd_base_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.nvd_base_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: sentinel_one_application_risk_nvd_cvss_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.nvd_cvss_version'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_os_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.os_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_published_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.published_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: sentinel_one_application_risk_reason
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.reason'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_remediation_level
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.remediation_level'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_report_confidence
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.report_confidence'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_risk_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: sentinel_one.application_risk.risk_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: sentinel_one_application_risk_severity
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.severity'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: sentinel_one_application_risk_status
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: sentinel_one.application_risk.status'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: vulnerability_cve
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: vulnerability.cve'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: vulnerability_package_published_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: vulnerability.package.published_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
