current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of traefik.access at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_origin_content_size
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.origin.content_size'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_origin_duration
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.origin.duration'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_origin_status_code
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.origin.status_code'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_origin_status_line
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.origin.status_line'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_overhead
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.overhead'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_request_count
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.request_count'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_retry_attempts
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.retry_attempts'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_router_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.router.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_address
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.address'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_duration
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: traefik.access.service.duration'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: traefik_access_service_url_domain
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.domain'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_force_query
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: traefik.access.service.url.force_query'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: traefik_access_service_url_fragment
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.fragment'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_opaque
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.opaque'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_original
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.original'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_path
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.path'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_query
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.query'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_raw_path
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.raw_path'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_raw_query
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.raw_query'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_scheme
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.scheme'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_service_url_user
      type: json
      attribute:
      - not_null
      cardinality: unknown
      expr: '@source: traefik.access.service.url.user'
      comment: 'Elasticsearch mapping type: group'
      _field_type: base
    - name: traefik_access_service_url_username
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.service.url.username'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: traefik_access_user_identifier
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: traefik.access.user_identifier'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
