current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of aws.config at integrations 2c934eb5223b
    columns:
    - name: aws_config_annotation
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.annotation'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_compliance_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.compliance_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_config_rule_invoked_time
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: aws.config.config_rule_invoked_time'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_evaluation_result_qualifier_config_rule_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.evaluation_result_identifier.evaluation_result_qualifier.config_rule_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_evaluation_result_qualifier_evaluation_mode
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.evaluation_result_identifier.evaluation_result_qualifier.evaluation_mode'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_evaluation_result_qualifier_resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.evaluation_result_identifier.evaluation_result_qualifier.resource_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_evaluation_result_qualifier_resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.evaluation_result_identifier.evaluation_result_qualifier.resource_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_ordering_timestamp
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: aws.config.evaluation_result_identifier.ordering_timestamp'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: aws_config_evaluation_result_identifier_resource_evaluation_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.evaluation_result_identifier.resource_evaluation_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_result_recorded_time
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: aws.config.result_recorded_time'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: aws_config_result_token
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.result_token'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_config_rule_arn
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.config_rule_arn'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_config_rule_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.config_rule_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_config_rule_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.config_rule_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_config_rule_state
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.config_rule_state'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_created_by
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.created_by'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_description
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.description'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_evaluation_modes_mode
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.evaluation_modes.mode'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_input_parameters
      type: json
      attribute:
      - not_null
      cardinality: unknown
      expr: '@source: aws.config.rule_info.input_parameters'
      comment: 'Elasticsearch mapping type: flattened'
      _field_type: base
    - name: aws_config_rule_info_maximum_execution_frequency
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.maximum_execution_frequency'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_scope_compliance_resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.scope.compliance_resource_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_scope_compliance_resource_types
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.scope.compliance_resource_types'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_scope_tag_key
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.scope.tag_key'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_scope_tag_value
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.scope.tag_value'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_custom_policy_details_enable_debug_log_delivery
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: aws.config.rule_info.source.custom_policy_details.enable_debug_log_delivery'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: aws_config_rule_info_source_custom_policy_details_policy_runtime
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.custom_policy_details.policy_runtime'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_custom_policy_details_policy_text
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.custom_policy_details.policy_text'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_owner
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.owner'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_source_details_event_source
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.source_details.event_source'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_source_details_maximum_execution_frequency
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.source_details.maximum_execution_frequency'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_source_details_message_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.source_details.message_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: aws_config_rule_info_source_source_identifier
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: aws.config.rule_info.source.source_identifier'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: result_evaluation
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: result.evaluation'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: rule_tags
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: rule.tags'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
