current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of wiz.cloud_configuration_finding_full_posture at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_sub_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.sub_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: result_evaluation
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: result.evaluation'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: result_evidence_cloud_configuration_link
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: result.evidence.cloud_configuration_link'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: result_evidence_configuration_path
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: result.evidence.configuration_path'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: result_evidence_current_value
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: result.evidence.current_value'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: result_evidence_expected_value
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: result.evidence.expected_value'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: rule_remediation
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: rule.remediation'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_analyzed_at
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: wiz.cloud_configuration_finding_full_posture.analyzed_at'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_evidence_cloud_configuration_link
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.evidence.cloud_configuration_link'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_evidence_configuration_path
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.evidence.configuration_path'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_evidence_current_value
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.evidence.current_value'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_evidence_expected_value
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.evidence.expected_value'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_cloud_platform
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.cloud_platform'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_native_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.native_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_provider_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.provider_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_region
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.region'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_subscription_cloud_provider
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.subscription.cloud_provider'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_subscription_external_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.subscription.external_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_subscription_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.subscription.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.resource.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_result
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.result'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_rule_description
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.rule.description'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_rule_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.rule.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_rule_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.rule.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_rule_remediation_instructions
      type: text
      cardinality: unknown
      use_case: word_search
      expr: '@source: wiz.cloud_configuration_finding_full_posture.rule.remediation_instructions'
      comment: 'Elasticsearch mapping type: text'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_rule_short_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.rule.short_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_status
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: wiz.cloud_configuration_finding_full_posture.status'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: wiz_cloud_configuration_finding_full_posture_updated_at
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: wiz.cloud_configuration_finding_full_posture.updated_at'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
