current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of azure.application_gateway at integrations 2c934eb5223b
    columns:
    - name: azure_application_gateway_action
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.action'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_hostname
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.hostname'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_instance_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.instance_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_operation_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.operation_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_policy_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.policy.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_policy_scope
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.policy.scope'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_policy_scope_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.policy.scope_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_application_gateway_transaction_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.application_gateway.transaction_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_correlation_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.correlation_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_authorization_rule
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.authorization_rule'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_group
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.group'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_namespace
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.namespace'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_resource_provider
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.resource.provider'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_subscription_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.subscription_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: azure_tenant_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: azure.tenant_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
