base: meta/elastic/ecs
base_version: "1.0.0"
current: "1.0.0"
versions:
  "1.0.0":
    date: "2026-10-04"
    summary: azure.application_gateway selection from meta/elastic/ecs
    select:
    - name: cloud_account_id
      index: exact_match
    - name: cloud_provider
      index: exact_match
    - name: data_stream_dataset
      index: exact_match
    - name: data_stream_namespace
      index: exact_match
    - name: data_stream_type
      index: exact_match
    - name: destination_address
      index: exact_match
    - name: destination_bytes
      index: range
    - name: destination_domain
      index: exact_match
    - name: ecs_version
      index: exact_match
    - name: event_action
      index: exact_match
    - name: event_category
      index: exact_match
    - name: event_dataset
      index: exact_match
    - name: event_kind
      index: exact_match
    - name: event_module
      index: exact_match
    - name: event_original
      index: none
    - name: event_reason
      index: exact_match
    - name: event_type
      index: exact_match
    - name: http_request_method
      index: exact_match
    - name: http_response_status_code
      index: range
    - name: http_version
      index: exact_match
    - name: message
      index: word_search
    - name: network_bytes
      index: range
    - name: network_protocol
      index: exact_match
    - name: observer_name
      index: exact_match
    - name: observer_product
      index: exact_match
    - name: observer_type
      index: exact_match
    - name: observer_vendor
      index: exact_match
    - name: related_hosts
      index: exact_match
    - name: related_ip
      index: dimension
    - name: rule_category
      index: exact_match
    - name: rule_description
      index: exact_match
    - name: rule_id
      index: exact_match
    - name: rule_ruleset
      index: exact_match
    - name: rule_version
      index: exact_match
    - name: source_address
      index: exact_match
    - name: source_bytes
      index: range
    - name: source_ip
      index: dimension
    - name: source_port
      index: range
    - name: tags
      index: exact_match
    - name: url_domain
      index: exact_match
    - name: url_path
      index: exact_match
    - name: url_query
      index: exact_match
