current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of tenable_sc.plugin at integrations 2c934eb5223b
    columns:
    - name: cloud_image_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: cloud.image.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_containerized
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: host.containerized'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: host_os_build
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.build'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_os_codename
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.codename'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: tenable_sc_plugin_base_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.base_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: tenable_sc_plugin_check_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.check_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_copyright
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.copyright'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_cpe
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.cpe'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_cvss_vector
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.cvss_vector'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_cvss_vector_bf
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.cvss_vector_bf'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_cvssv3_base_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.cvssv3_base_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: tenable_sc_plugin_cvssv3_temporal_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.cvssv3_temporal_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: tenable_sc_plugin_cvssv3_vector
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.cvssv3_vector'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_cvssv3_vector_bf
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.cvssv3_vector_bf'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_dependencies
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.dependencies'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_description
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.description'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_dst_port
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.dst_port'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: tenable_sc_plugin_exploit_ease
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.exploit.ease'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_exploit_frameworks
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.exploit.frameworks'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_exploit_is_available
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.exploit.is_available'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_family_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.family.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_family_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.family.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_family_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.family.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_is_patch_modified
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.is_patch_modified'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_is_patch_published
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.is_patch_published'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_is_plugin_modified
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.is_plugin_modified'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_is_plugin_published
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.is_plugin_published'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_is_vulnerability_published
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: tenable_sc.plugin.is_vulnerability_published'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: tenable_sc_plugin_md5
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.md5'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_modified_time
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.modified_time'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_patch_mod_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.patch_mod_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_patch_pub_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.patch_pub_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_plugin_mod_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.plugin_mod_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_plugin_pub_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.plugin_pub_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_protocol
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.protocol'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_required_ports
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.required_ports'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_required_udp_ports
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.required_udp_ports'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_risk_factor
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.risk_factor'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_see_also
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.see_also'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_solution
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.solution'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_source
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.source'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_source_file
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.source_file'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_src_port
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.src_port'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: tenable_sc_plugin_stig_severity
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.stig_severity'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_synopsis
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.synopsis'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_temporal_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.temporal_score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: tenable_sc_plugin_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: tenable_sc_plugin_version
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.version'
      comment: 'Elasticsearch mapping type: version'
      _field_type: base
    - name: tenable_sc_plugin_vpr_context
      type: json
      attribute:
      - not_null
      cardinality: unknown
      expr: '@source: tenable_sc.plugin.vpr.context'
      comment: 'Elasticsearch mapping type: flattened'
      _field_type: base
    - name: tenable_sc_plugin_vpr_score
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.vpr.score'
      comment: 'Elasticsearch mapping type: double'
      _field_type: base
    - name: tenable_sc_plugin_vuln_pub_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: tenable_sc.plugin.vuln_pub_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: tenable_sc_plugin_xrefs
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: tenable_sc.plugin.xrefs'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
