current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of prisma_cloud.misconfiguration at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_account_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.account_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_account_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.account_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_alert_status_critical
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: prisma_cloud.misconfiguration.alert_status.critical'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_alert_status_high
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: prisma_cloud.misconfiguration.alert_status.high'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_alert_status_informational
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: prisma_cloud.misconfiguration.alert_status.informational'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_alert_status_low
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: prisma_cloud.misconfiguration.alert_status.low'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_alert_status_medium
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: prisma_cloud.misconfiguration.alert_status.medium'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: prisma_cloud_misconfiguration_app_names
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.app_names'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_asset_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.asset_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_cloud_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.cloud_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_overall_passed
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: prisma_cloud.misconfiguration.overall_passed'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: prisma_cloud_misconfiguration_region_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.region_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_region_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.region_name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_resource_config_json_available
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: prisma_cloud.misconfiguration.resource_config_json_available'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: prisma_cloud_misconfiguration_resource_details_available
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: prisma_cloud.misconfiguration.resource_details_available'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: prisma_cloud_misconfiguration_rrn
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.rrn'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_scanned_policy_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.scanned_policy.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_scanned_policy_labels
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.scanned_policy.labels'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_scanned_policy_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.scanned_policy.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_scanned_policy_passed
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: prisma_cloud.misconfiguration.scanned_policy.passed'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: prisma_cloud_misconfiguration_scanned_policy_severity
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.scanned_policy.severity'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: prisma_cloud_misconfiguration_unified_asset_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: prisma_cloud.misconfiguration.unified_asset_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: resource.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: result_evaluation
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: result.evaluation'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: rule_tags
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: rule.tags'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
