current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of mongodb_atlas.project at integrations 2c934eb5223b
    columns:
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_additional_info
      type: json
      attribute:
      - not_null
      cardinality: unknown
      expr: '@source: mongodb_atlas.project.additional_info'
      comment: 'Elasticsearch mapping type: flattened'
      _field_type: base
    - name: mongodb_atlas_project_alert_config_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.alert.config.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_alert_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.alert.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_api_key_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.api_key.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_application_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.application.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_application_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.application.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_cluster_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.cluster.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_cluster_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.cluster.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_collection_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.collection.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_database_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.database.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_database_username
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.database.username'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_endpoint_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.endpoint.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_event_type_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.event_type.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_host_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.host.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_host_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.host.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_invoice_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.invoice.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_is_global_admin
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: mongodb_atlas.project.is_global_admin'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: mongodb_atlas_project_metric_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.metric.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_metric_unit
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.metric.unit'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_metric_value
      type: float
      cardinality: unknown
      use_case: range
      expr: '@source: mongodb_atlas.project.metric.value'
      comment: 'Elasticsearch mapping type: float'
      _field_type: base
    - name: mongodb_atlas_project_operation_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.operation.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_payment_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.payment.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_processor_error_msg
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.processor.error_msg'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_processor_instance_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.processor.instance.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_processor_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.processor.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_processor_state
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.processor.state'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_provider_endpoint_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.provider_endpoint.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_public_key
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.public_key'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_replicaset_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.replicaset.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_resource_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.resource.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_resource_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.resource.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_shard_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.shard.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_snapshot_completion_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: mongodb_atlas.project.snapshot.completion_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: mongodb_atlas_project_snapshot_frequency_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.snapshot.frequency_type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_snapshot_scheduled_creation_date
      type: datetime
      cardinality: unknown
      use_case: range
      expr: '@source: mongodb_atlas.project.snapshot.scheduled_creation_date'
      comment: 'Elasticsearch mapping type: date'
      _field_type: base
    - name: mongodb_atlas_project_target_public_key
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.target_public_key'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_target_username
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.target.username'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_team_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.team.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: mongodb_atlas_project_whitelist_entry
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: mongodb_atlas.project.whitelist_entry'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
