current: "1.0.0"
resource_type: core
versions:
  "1.0.0":
    date: "2026-10-04"
    type: model
    summary: Vendor fields of kubernetes.container_logs at integrations 2c934eb5223b
    columns:
    - name: cloud_image_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: cloud.image.id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_containerized
      type: boolean
      cardinality: unknown
      use_case: dimension
      expr: '@source: host.containerized'
      comment: 'Elasticsearch mapping type: boolean'
      _field_type: base
    - name: host_os_build
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.build'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: host_os_codename
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: host.os.codename'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: input_type
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: input.type'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_container_image
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.container.image'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_container_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.container.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_cronjob_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.cronjob.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_daemonset_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.daemonset.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_deployment_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.deployment.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_job_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.job.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_namespace
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.namespace'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_namespace_uid
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.namespace_uid'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_node_hostname
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.node.hostname'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_node_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.node.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_node_uid
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.node.uid'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_pod_ip
      type: ip
      cardinality: unknown
      use_case: dimension
      expr: '@source: kubernetes.pod.ip'
      comment: 'Elasticsearch mapping type: ip'
      _field_type: base
    - name: kubernetes_pod_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.pod.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_pod_uid
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.pod.uid'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_replicaset_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.replicaset.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: kubernetes_statefulset_name
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: kubernetes.statefulset.name'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_file_device_id
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: log.file.device_id'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_file_fingerprint
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: log.file.fingerprint'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_file_inode
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: log.file.inode'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
    - name: log_offset
      type: integer
      cardinality: unknown
      use_case: range
      expr: '@source: log.offset'
      comment: 'Elasticsearch mapping type: long'
      _field_type: base
    - name: stream
      type: string
      cardinality: unknown
      use_case: exact_match
      expr: '@source: stream'
      comment: 'Elasticsearch mapping type: keyword'
      _field_type: base
