-- =============================================================================
-- DFE Schema DDL: dfe_hunts.detection
-- Profile: timeseries
-- Hunt detection results (profile + detection columns)
-- Generated by: dfe-engine DDLFileWriter
--
-- This file is auto-generated. Use {db} as database placeholder.
-- =============================================================================
CREATE TABLE IF NOT EXISTS {db}.detection
(
    `_timestamp_load` DateTime64(3,'UTC') DEFAULT now64(3) CODEC(Delta, LZ4) COMMENT '@generated: now64(3) — Insertion timestamp (ms precision)',
    `_timestamp` DateTime64(3,'UTC') CODEC(Delta, LZ4) COMMENT '@source: timestamp | now() — Event timestamp from source data',
    `_timestamp_received` DateTime64(3,'UTC') CODEC(Delta, LZ4) COMMENT '@source: first(timestamp_received/received_at) — When the event was first received by the receiver',
    `_uuid` Nullable(UUID) DEFAULT generateUUIDv7() COMMENT '@generated: generateUUIDv7() — Time-ordered unique event identifier',
    `_org_id` LowCardinality(String) CODEC(ZSTD(1)) COMMENT '@source: org_id — Tenant/organisation identifier',
    `_source` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT '@source: first(_source) | topic_name — Data source label (e.g. beats, syslog, crowdstrike_edr)',
    `_json` Nullable(JSON) CODEC(ZSTD(3)) COMMENT '@captured: raw_payload as JSON — Original event payload as structured JSON',
    `matched_uuid` Nullable(UUID) COMMENT 'UUID of the matching source record',
    `rule_id` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT 'Rule identifier',
    `rule_name` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT 'Human-readable rule name',
    `source_table` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT 'Source table that was scanned',
    `hunt_name` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT 'Parent hunt name',
    `severity` LowCardinality(Nullable(String)) CODEC(ZSTD(1)) COMMENT 'Detection severity',
    INDEX idx__timestamp `_timestamp` TYPE minmax GRANULARITY 4,
    INDEX idx__org_id `_org_id` TYPE set(0) GRANULARITY 4,
    INDEX idx__source `_source` TYPE set(0) GRANULARITY 4,
    PROJECTION timestamp_optimized (SELECT * ORDER BY `_timestamp`)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(_timestamp_load)
PRIMARY KEY (`_timestamp_load`, `_timestamp`, `_org_id`)
ORDER BY (`_timestamp_load`, `_timestamp`, `_org_id`)
TTL _timestamp + INTERVAL 365 DAY DELETE WHERE _timestamp >= 0,
    _timestamp_load + INTERVAL 365 DAY DELETE WHERE _timestamp_load >= 0
COMMENT '@schema_version: 2 | @profile: timeseries | @profile_version: 1.0.0'
SETTINGS
    index_granularity = 2048,
    ttl_only_drop_parts = 1;
